pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/kapubindureddy/kapubindureddy.git/myapp'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Completed') {
            steps {
                echo 'Build successful!'
            }
        }
    }
}

